version: "3.8"

services:
  web:
    build: ./webapp
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      ./webapp/test_task/.env
    ports:
      - 8000:8000

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rocketdata

  redis:
    image: redis
    restart: always

  worker:
    build: ./webapp
    command: ['celery', '--workdir=./', '-A', 'test_task', 'worker']

volumes:
  postgres_data:

