# Generated by Django 4.1.3 on 2022-11-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_factory_product_alter_dilercenter_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindistributor',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='productindistributor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinindividualentrepreneur',
            name='individual_entrepreneur',
        ),
        migrations.RemoveField(
            model_name='productinindividualentrepreneur',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinretailchain',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinretailchain',
            name='retail_chain',
        ),
        migrations.AddField(
            model_name='dilercenter',
            name='product',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='product',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='product',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.AddField(
            model_name='retailchain',
            name='product',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.DeleteModel(
            name='ProductInDilercenter',
        ),
        migrations.DeleteModel(
            name='ProductInDistributor',
        ),
        migrations.DeleteModel(
            name='ProductInIndividualEntrepreneur',
        ),
        migrations.DeleteModel(
            name='ProductInRetailChain',
        ),
    ]
