# Generated by Django 4.1.3 on 2022-11-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_employee_remove_employeedistributor_distributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dilercenter',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='retailchain',
            name='employee',
        ),
        migrations.AddField(
            model_name='dilercenter',
            name='employee',
            field=models.ManyToManyField(to='app.employee'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='employee',
            field=models.ManyToManyField(to='app.employee'),
        ),
        migrations.AddField(
            model_name='factory',
            name='employee',
            field=models.ManyToManyField(to='app.employee'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='employee',
            field=models.ManyToManyField(to='app.employee'),
        ),
        migrations.AddField(
            model_name='retailchain',
            name='employee',
            field=models.ManyToManyField(to='app.employee'),
        ),
    ]
