# Generated by Django 4.1.3 on 2022-11-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app.address')),
            ],
        ),
    ]
