# Generated by Django 4.1.3 on 2022-11-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app.address'),
        ),
    ]
