# Generated by Django 4.1.3 on 2022-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_factory_employeefactory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
