# Generated by Django 4.1.3 on 2022-11-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_factory_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductInFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory', to='app.factory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.product')),
            ],
        ),
    ]
