# Generated by Django 4.1.3 on 2022-11-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_factory_product_productinfactory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dilercenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_dilercenter', to='app.contact')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_field', to='app.factory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInDilercenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilercenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dilercenter', to='app.dilercenter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dilercenter', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDilercenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('dilercenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dilercenter')),
            ],
        ),
    ]
