# Generated by Django 4.1.3 on 2022-11-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dilercenter_productindilercenter_employeedilercenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_distributor', to='app.contact')),
            ],
        ),
        migrations.AlterField(
            model_name='dilercenter',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductInDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to='app.dilercenter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_distributor', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distributor')),
            ],
        ),
        migrations.AddField(
            model_name='distributor',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dilercenter_field', to='app.dilercenter'),
        ),
    ]
