# Generated by Django 4.1.3 on 2022-11-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_productindistributor_distributor_retailchain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_individual_entrepreneur', to='app.contact')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_chain_field', to='app.retailchain')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInIndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_entrepreneur', to='app.individualentrepreneur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_individual_entrepreneur', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('individual_entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.individualentrepreneur')),
            ],
        ),
    ]
