# Generated by Django 4.1.3 on 2022-11-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_productindistributor_distributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeedistributor',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='employeefactory',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='employeeindividualentrepreneur',
            name='individual_entrepreneur',
        ),
        migrations.RemoveField(
            model_name='employeeretailchain',
            name='retail_chain',
        ),
        migrations.DeleteModel(
            name='EmployeeDilercenter',
        ),
        migrations.DeleteModel(
            name='EmployeeDistributor',
        ),
        migrations.DeleteModel(
            name='EmployeeFactory',
        ),
        migrations.DeleteModel(
            name='EmployeeIndividualEntrepreneur',
        ),
        migrations.DeleteModel(
            name='EmployeeRetailChain',
        ),
        migrations.AddField(
            model_name='dilercenter',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_dilercenter', to='app.employee'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_distributor', to='app.employee'),
        ),
        migrations.AddField(
            model_name='factory',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_factory', to='app.employee'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_individual_entrepreneur', to='app.employee'),
        ),
        migrations.AddField(
            model_name='retailchain',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_retail_chain', to='app.employee'),
        ),
    ]
