# Generated by Django 4.1.3 on 2022-11-07 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_alter_dilercenter_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dilercenter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailchain',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='app.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=20, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=20, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='dilercenter',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_dilercenter', to='app.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='dilercenter',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dilercenter',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Задолжность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='dilercenter',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dilercenter',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_field', to='app.factory', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_distributor', to='app.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Задолжность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dilercenter_field', to='app.dilercenter', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=254, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='app.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Долг перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_individual_entrepreneur', to='app.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Задолжность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_chain_field', to='app.retailchain', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=254, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_retail_chain', to='app.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Задолжность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_field', to='app.distributor', verbose_name='Поставщик'),
        ),
    ]
